package com.example.recipedecoderapp

object MealRepository {
    private val mealSuggestions = listOf(
        "Grilled Chicken Salad",
        "Quinoa & Vegetable Bowl",
        "Baked Salmon with Asparagus",
        "Veggie Stir-Fry with Tofu",
        "Turkey Wrap with Avocado",
        "Zucchini Noodles with Pesto",
        "Chickpea & Spinach Curry",
        "Stuffed Bell Peppers",
        "Baked Cod with Lemon",
        "Lentil Soup",
        "Cauliflower Rice Bowl",
        "Greek Salad with Feta",
        "Grilled Shrimp Skewers",
        "Spinach & Feta Omelette",
        "Whole Wheat Pasta Primavera",
        "Veggie Burger on a Whole Grain Bun",
        "Chicken Avocado Wrap",
        "Black Bean Soup",
        "Baked Sweet Potato with Cottage Cheese",
        "Eggplant Parmesan Light",
        "Tofu and Broccoli Stir-fry",
        "Mediterranean Quinoa Salad",
        "Roasted Brussels Sprouts with Chicken",
        "Mason Jar Salad",
        "Pumpkin Soup",
        "Balsamic Glazed Chicken",
        "Cabbage Stir Fry",
        "Couscous Salad with Veggies",
        "Fish Tacos with Mango Salsa",
        "Thai Basil Chicken",
        "Spinach and Mushroom Quesadilla",
        "Avocado Toast with Poached Egg",
        "Roasted Vegetable Medley",
        "Pesto Zucchini Pasta",
        "Chicken and Vegetable Skewers",
        "Black Bean and Corn Salad",
        "Grilled Turkey Burgers",
        "Vegetable Frittata",
        "Roasted Beet Salad",
        "Quinoa Stuffed Bell Peppers",
        "Shrimp and Avocado Salad",
        "Grilled Portobello Mushrooms",
        "Baked Tilapia with Veggies",
        "Minestrone Soup",
        "Falafel Wrap",
        "Cucumber and Tomato Salad",
        "Chicken and Broccoli Stir-Fry",
        "Vegetable Paella",
        "Grilled Pork Tenderloin",
        "Butternut Squash Soup",
        "Kale Salad with Lemon Vinaigrette",
        "Roasted Chicken with Veggies",
        "Spinach Salad with Strawberries",
        "Lentil and Tomato Stew",
        "Grilled Vegetable Sandwich",
        "Crispy Tofu with Peanut Sauce",
        "Mushroom Risotto",
        "Shrimp & Broccoli Stir-Fry",
        "Grilled Chicken with Mango Salsa",
        "Chili Lime Cauliflower Bites",
        "Veggie-Packed Fajitas",
        "Seared Tuna Salad",
        "Roasted Red Pepper Soup",
        "Grilled Lamb Chops",
        "Zoodle Bolognese",
        "Spinach and Ricotta Stuffed Shells",
        "Chicken Caesar Salad Light",
        "Moroccan Chickpea Stew",
        "Veggie Pizza on Cauliflower Crust",
        "Quinoa and Black Bean Salad",
        "Herbed Baked Chicken Breast",
        "Roasted Eggplant and Tomato Pasta",
        "Vegetable Curry with Brown Rice",
        "Grilled Fish with Herbs",
        "Vegetarian Sushi Rolls",
        "Sweet Potato and Black Bean Tacos",
        "Mediterranean Veggie Wrap",
        "Lemon Herb Quinoa with Veggies",
        "Crispy Baked Falafel",
        "Chicken and Spinach Stuffed Sweet Potato",
        "Warm Farro Salad",
        "Zesty Lime Chicken Salad",
        "Roasted Turkey Breast with Veggies",
        "Chickpea Salad Sandwich",
        "Quinoa Bowl with Avocado",
        "Garlic Shrimp with Broccoli",
        "Steamed Fish with Ginger",
        "Tomato Basil Soup",
        "Grilled Veggie and Hummus Wrap",
        "Spicy Lentil Curry",
        "Broccoli and Cheddar Stuffed Chicken",
        "Cauliflower Steak",
        "Healthy Chicken Alfredo with Zoodles",
        "Miso Soup with Tofu",
        "Spinach and Mushroom Pasta",
        "Vegan Burrito Bowl",
        "Grilled Chicken with Quinoa Salad",
        "Steak Salad with Arugula",
        "Roasted Vegetable Quinoa",
        "Shrimp Avocado Bowl"
    )

    fun getRandomMeals(count: Int = 3): List<String> {
        return mealSuggestions.shuffled().take(count)
    }
}
